# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb    
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USER: postgres          # Username
      POSTGRES_PASSWORD: mysecretpassword
   
volumes:
  pgdata:
