version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_USER: papaya
      POSTGRES_PASSWORD: lectora
      POSTGRES_DB: la_santa_biblioteca
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

